fix: update README.md
skb1129/react-native-change-icon pull request #76
Opened 2022-11-16 01:42 UTC by tvc97

2022-11-17 13:38 UTC, WrathChaos approved these changes

2022-11-17 13:52 UTC, WrathChaos requested changes
I found that if you check `Include all app icon assets` into the `App Icons and Launch Screen` it simply does not work. It cannot change the app icon

2022-11-18 01:44 UTC, tvc97 commented
> I found that if you check `Include all app icon assets` into the `App Icons and Launch Screen` it simply does not work. It cannot change the app icon
 
@WrathChaosư Doesn't work without checking the box in my case

2023-08-18 12:45 UTC, skb1129 commented
docs are updated, not required anymore

2023-08-18 12:45 UTC, closed without merging